package com.binance.strategy;

import com.binance.strategy.CtiScoreCalculator.RecReason;

	public record ScoreSignal(
			CtiDirection cti1mDir,
			CtiDirection cti5mDir,
			int hamCtiScore,
			int ctiDirScore,
			double ctiScore,
			double macdScore,
			double outHist,
			double outHistPrev,
			double finalScore,
			int score1m,
			int score5m,
			double cti1mValue,
			double cti1mPrev,
			Double cti5mValue,
			Double cti5mPrev,
			Double adx5m,
			Double adxSma10,
			Boolean drop3,
			Boolean crossDown,
			Boolean belowSma,
			Boolean deadZone,
			Double adxExitPressure,
			MacdHistColor macdHistColor,
			double trendWeight,
			double adjustedScore,
			CtiDirection recommendation,
			CtiDirection bias,
			RecReason recReason,
			boolean adxGate,
			boolean adxReady,
			String adxGateReason,
			boolean cti5mReady,
			int cti5mBarsSeen,
			int cti5mPeriod,
			int adx5mBarsSeen,
			int adx5mPeriod,
			long t5mCloseUsed,
			long closeTime,
			boolean insufficientData) {
	}
